-- Studio Ferreira — Agenda online v1
-- Execute este arquivo inteiro no SQL Editor do Supabase.

create extension if not exists btree_gist;

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  category text not null,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  duration_minutes integer not null check (duration_minutes between 15 and 480),
  deposit_percent numeric(5,2) not null default 40 check (deposit_percent between 0 and 100),
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_hours (
  id bigint generated by default as identity primary key,
  day_of_week smallint not null unique check (day_of_week between 0 and 6),
  open_time time not null default '08:00',
  close_time time not null default '19:00',
  slot_interval_minutes integer not null default 30 check (slot_interval_minutes between 15 and 240),
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  check (close_time > open_time)
);

create table if not exists public.blocked_times (
  id uuid primary key default gen_random_uuid(),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id),
  customer_name text not null check (char_length(customer_name) between 3 and 120),
  customer_phone text not null,
  customer_phone_digits text not null check (char_length(customer_phone_digits) between 10 and 13),
  notes text check (notes is null or char_length(notes) <= 800),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending','confirmed','completed','cancelled','no_show')),
  service_name_snapshot text not null,
  price_snapshot numeric(10,2) not null,
  deposit_percent_snapshot numeric(5,2) not null,
  deposit_amount_snapshot numeric(10,2) not null,
  source text not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Impede sobreposição de horários confirmados ou aguardando confirmação,
-- inclusive quando duas clientes tentam reservar simultaneamente.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'appointments_no_overlap'
  ) then
    alter table public.appointments
      add constraint appointments_no_overlap
      exclude using gist (
        tstzrange(starts_at, ends_at, '[)') with &&
      ) where (status in ('pending','confirmed'));
  end if;
end $$;

create index if not exists appointments_starts_at_idx on public.appointments(starts_at);
create index if not exists appointments_status_idx on public.appointments(status);
create index if not exists appointments_phone_idx on public.appointments(customer_phone_digits);
create index if not exists blocked_times_starts_at_idx on public.blocked_times(starts_at);
create index if not exists services_active_order_idx on public.services(active, display_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services
for each row execute function public.set_updated_at();

drop trigger if exists business_hours_set_updated_at on public.business_hours;
create trigger business_hours_set_updated_at before update on public.business_hours
for each row execute function public.set_updated_at();

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at before update on public.appointments
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

create or replace function public.get_available_slots(
  p_service_id uuid,
  p_date date
)
returns table(slot_time time, label text)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_duration integer;
  v_open time;
  v_close time;
  v_interval integer;
  v_day smallint;
  v_timezone constant text := 'America/Sao_Paulo';
begin
  if p_date < current_date or p_date > current_date + 120 then
    return;
  end if;

  select duration_minutes into v_duration
  from public.services
  where id = p_service_id and active = true;

  if v_duration is null then
    return;
  end if;

  v_day := extract(dow from p_date)::smallint;

  select open_time, close_time, slot_interval_minutes
    into v_open, v_close, v_interval
  from public.business_hours
  where day_of_week = v_day and active = true;

  if v_open is null then
    return;
  end if;

  return query
  with candidates as (
    select gs as local_start,
           gs + make_interval(mins => v_duration) as local_end
    from generate_series(
      p_date + v_open,
      p_date + v_close - make_interval(mins => v_duration),
      make_interval(mins => v_interval)
    ) as gs
  )
  select c.local_start::time as slot_time,
         to_char(c.local_start, 'HH24:MI') as label
  from candidates c
  where (c.local_start at time zone v_timezone) > now()
    and not exists (
      select 1
      from public.appointments a
      where a.status in ('pending','confirmed')
        and tstzrange(a.starts_at, a.ends_at, '[)') &&
            tstzrange(
              c.local_start at time zone v_timezone,
              c.local_end at time zone v_timezone,
              '[)'
            )
    )
    and not exists (
      select 1
      from public.blocked_times b
      where tstzrange(b.starts_at, b.ends_at, '[)') &&
            tstzrange(
              c.local_start at time zone v_timezone,
              c.local_end at time zone v_timezone,
              '[)'
            )
    )
  order by c.local_start;
end;
$$;

create or replace function public.create_public_appointment(
  p_service_id uuid,
  p_date date,
  p_start_time time,
  p_customer_name text,
  p_customer_phone text,
  p_notes text default null
)
returns table(
  appointment_id uuid,
  service_name text,
  price numeric,
  deposit_amount numeric,
  starts_at timestamptz,
  ends_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_service public.services%rowtype;
  v_phone_digits text;
  v_start timestamptz;
  v_end timestamptz;
  v_id uuid;
  v_timezone constant text := 'America/Sao_Paulo';
begin
  select * into v_service
  from public.services
  where id = p_service_id and active = true;

  if not found then
    raise exception 'SERVICO_INDISPONIVEL';
  end if;

  if trim(coalesce(p_customer_name, '')) = '' or char_length(trim(p_customer_name)) < 3 then
    raise exception 'NOME_INVALIDO';
  end if;

  v_phone_digits := regexp_replace(coalesce(p_customer_phone, ''), '\D', '', 'g');
  if char_length(v_phone_digits) < 10 or char_length(v_phone_digits) > 13 then
    raise exception 'TELEFONE_INVALIDO';
  end if;

  if not exists (
    select 1 from public.get_available_slots(p_service_id, p_date)
    where slot_time = p_start_time
  ) then
    raise exception 'HORARIO_INDISPONIVEL';
  end if;

  -- Reduz envios duplicados acidentais do mesmo telefone.
  if exists (
    select 1 from public.appointments
    where customer_phone_digits = v_phone_digits
      and created_at > now() - interval '90 seconds'
  ) then
    raise exception 'AGUARDE_ANTES_DE_ENVIAR_NOVAMENTE';
  end if;

  v_start := (p_date + p_start_time) at time zone v_timezone;
  v_end := v_start + make_interval(mins => v_service.duration_minutes);

  begin
    insert into public.appointments (
      service_id,
      customer_name,
      customer_phone,
      customer_phone_digits,
      notes,
      starts_at,
      ends_at,
      status,
      service_name_snapshot,
      price_snapshot,
      deposit_percent_snapshot,
      deposit_amount_snapshot,
      source
    ) values (
      v_service.id,
      trim(p_customer_name),
      trim(p_customer_phone),
      v_phone_digits,
      nullif(trim(coalesce(p_notes, '')), ''),
      v_start,
      v_end,
      'pending',
      v_service.name,
      v_service.price,
      v_service.deposit_percent,
      round(v_service.price * v_service.deposit_percent / 100, 2),
      'website'
    ) returning id into v_id;
  exception
    when exclusion_violation then
      raise exception 'HORARIO_INDISPONIVEL';
  end;

  return query
  select
    v_id,
    v_service.name,
    v_service.price,
    round(v_service.price * v_service.deposit_percent / 100, 2),
    v_start,
    v_end;
end;
$$;

create or replace function public.admin_create_block(
  p_date date,
  p_start_time time,
  p_end_time time,
  p_reason text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_timezone constant text := 'America/Sao_Paulo';
begin
  if not public.is_admin() then
    raise exception 'ACESSO_NEGADO';
  end if;
  if p_end_time <= p_start_time then
    raise exception 'INTERVALO_INVALIDO';
  end if;

  insert into public.blocked_times(starts_at, ends_at, reason)
  values (
    (p_date + p_start_time) at time zone v_timezone,
    (p_date + p_end_time) at time zone v_timezone,
    nullif(trim(coalesce(p_reason, '')), '')
  ) returning id into v_id;

  return v_id;
end;
$$;

-- Segurança por linha
alter table public.services enable row level security;
alter table public.business_hours enable row level security;
alter table public.blocked_times enable row level security;
alter table public.appointments enable row level security;
alter table public.admin_users enable row level security;

-- Remove políticas anteriores deste projeto, caso o arquivo seja executado novamente.
do $$
declare p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('services','business_hours','blocked_times','appointments','admin_users')
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

create policy "Public can read active services"
on public.services for select
to anon, authenticated
using (active = true or public.is_admin());

create policy "Admins manage services"
on public.services for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins read business hours"
on public.business_hours for select
to authenticated
using (public.is_admin());

create policy "Admins manage business hours"
on public.business_hours for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins manage blocked times"
on public.blocked_times for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins manage appointments"
on public.appointments for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "User can read own admin membership"
on public.admin_users for select
to authenticated
using (user_id = (select auth.uid()));

revoke all on public.appointments from anon;
revoke all on public.blocked_times from anon;
revoke all on public.business_hours from anon;
revoke insert, update, delete on public.services from anon;

grant select on public.services to anon, authenticated;
grant select, insert, update, delete on public.services to authenticated;
grant select, insert, update, delete on public.business_hours to authenticated;
grant select, insert, update, delete on public.blocked_times to authenticated;
grant select, insert, update, delete on public.appointments to authenticated;
grant select on public.admin_users to authenticated;

grant execute on function public.get_available_slots(uuid, date) to anon, authenticated;
grant execute on function public.create_public_appointment(uuid, date, time, text, text, text) to anon, authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.admin_create_block(date, time, time, text) to authenticated;

-- Serviços iniciais. As durações são ajustáveis pelo painel administrativo.
insert into public.services (slug, category, name, price, duration_minutes, deposit_percent, display_order)
values
('cilios-brasileiro-colocacao','Extensão de cílios','Cílios Brasileiro — Colocação',120,120,40,10),
('cilios-brasileiro-manutencao','Extensão de cílios','Cílios Brasileiro — Manutenção',90,90,40,11),
('cilios-3d-colocacao','Extensão de cílios','Cílios 3D — Colocação',130,120,40,20),
('cilios-3d-manutencao','Extensão de cílios','Cílios 3D — Manutenção',90,90,40,21),
('cilios-4d-colocacao','Extensão de cílios','Cílios 4D — Colocação',140,120,40,30),
('cilios-4d-manutencao','Extensão de cílios','Cílios 4D — Manutenção',100,90,40,31),
('cilios-5d-colocacao','Extensão de cílios','Cílios 5D — Colocação',150,120,40,40),
('cilios-5d-manutencao','Extensão de cílios','Cílios 5D — Manutenção',100,90,40,41),
('cilios-6d-colocacao','Extensão de cílios','Cílios 6D — Colocação',160,120,40,50),
('cilios-6d-manutencao','Extensão de cílios','Cílios 6D — Manutenção',110,90,40,51),
('cilios-8d-colocacao','Extensão de cílios','Cílios 8D — Colocação',180,120,40,60),
('cilios-8d-manutencao','Extensão de cílios','Cílios 8D — Manutenção',130,90,40,61),
('cilios-fox-colocacao','Extensão de cílios','Cílios Fox — Colocação',150,120,40,70),
('cilios-fox-manutencao','Extensão de cílios','Cílios Fox — Manutenção',100,90,40,71),
('cilios-marrom-colocacao','Extensão de cílios','Cílios Marrom — Colocação',140,120,40,80),
('cilios-marrom-manutencao','Extensão de cílios','Cílios Marrom — Manutenção',100,90,40,81),
('unhas-fibra-colocacao','Unhas','Unhas de Fibra — Colocação',160,120,40,90),
('unhas-fibra-manutencao','Unhas','Unhas de Fibra — Manutenção',100,90,40,91),
('unhas-molde-f1-colocacao','Unhas','Molde F1 — Colocação',140,120,40,100),
('unhas-molde-f1-manutencao','Unhas','Molde F1 — Manutenção',90,90,40,101),
('unhas-esmaltacao-gel','Unhas','Esmaltação em gel',50,60,40,110),
('sobrancelha-henna','Sobrancelhas','Sobrancelha com henna',40,45,40,120),
('sobrancelha-design','Sobrancelhas','Design simples de sobrancelha',30,30,40,121)
on conflict (slug) do update set
  category = excluded.category,
  name = excluded.name,
  price = excluded.price,
  duration_minutes = excluded.duration_minutes,
  deposit_percent = excluded.deposit_percent,
  display_order = excluded.display_order;

insert into public.business_hours(day_of_week, open_time, close_time, slot_interval_minutes, active)
values
(0,'08:00','18:00',30,false),
(1,'08:00','19:00',30,true),
(2,'08:00','19:00',30,true),
(3,'08:00','19:00',30,true),
(4,'08:00','19:00',30,true),
(5,'08:00','19:00',30,true),
(6,'08:00','18:00',30,true)
on conflict (day_of_week) do nothing;

-- Depois de criar a usuária em Authentication > Users, rode separadamente:
-- insert into public.admin_users(user_id)
-- select id from auth.users where email = 'EMAIL_DA_VITORIA';
